### ISSUE TITLE
Error with creating IAM policy

### ISSUE THREAD

**Issue by SynitiSmug** [basisai/terraform-aws-lb-controller#5]
This error occurs when attempting to run the module:
`│ Error: error creating IAM Role (aws-load-balancer-controller): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, CreateRoleInput.Path.
│ 
│ 
│   with module.eks.module.lb-controller.module.iam_assumable_role_admin.aws_iam_role.this[0],
│   on .terraform/modules/eks.lb-controller.iam_assumable_role_admin/modules/iam-assumable-role-with-oidc/main.tf line 65, in resource "aws_iam_role" "this":
│   65: resource "aws_iam_role" "this" {`

The fix for me was to remove the `path` attribute from `main.tf` and this allowed the role to be created.  I can create a PR with the proposed fix.

**Comment by lawliet89** [comment]
Did you manage to fix this? We need the `path` for some other use case, though. If you leave it as the default value it should work as-is.

**Comment by SynitiSmug** [comment]
sorry, this issue was with a submodule, not yours.  I closed it.
